// Code generated by mockery v2.26.1. DO NOT EDIT.

package mocks

import "github.com/stretchr/testify/mock"

// HealthCheck is an autogenerated mock type for the HealthCheck type
type HealthCheck struct {
	mock.Mock
}

type HealthCheck_Expecter struct {
	mock *mock.Mock
}

func (_m *HealthCheck) EXPECT() *HealthCheck_Expecter {
	return &HealthCheck_Expecter{mock: &_m.Mock}
}

// GetName provides a mock function with given fields:
func (_m *HealthCheck) GetName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// HealthCheck_GetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetName'
type HealthCheck_GetName_Call struct {
	*mock.Call
}

// GetName is a helper method to define mock.On call
func (_e *HealthCheck_Expecter) GetName() *HealthCheck_GetName_Call {
	return &HealthCheck_GetName_Call{Call: _e.mock.On("GetName")}
}

func (_c *HealthCheck_GetName_Call) Run(run func()) *HealthCheck_GetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HealthCheck_GetName_Call) Return(_a0 string) *HealthCheck_GetName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HealthCheck_GetName_Call) RunAndReturn(run func() string) *HealthCheck_GetName_Call {
	_c.Call.Return(run)
	return _c
}

// HealthCheck provides a mock function with given fields:
func (_m *HealthCheck) HealthCheck() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HealthCheck_HealthCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HealthCheck'
type HealthCheck_HealthCheck_Call struct {
	*mock.Call
}

// HealthCheck is a helper method to define mock.On call
func (_e *HealthCheck_Expecter) HealthCheck() *HealthCheck_HealthCheck_Call {
	return &HealthCheck_HealthCheck_Call{Call: _e.mock.On("HealthCheck")}
}

func (_c *HealthCheck_HealthCheck_Call) Run(run func()) *HealthCheck_HealthCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HealthCheck_HealthCheck_Call) Return(_a0 error) *HealthCheck_HealthCheck_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HealthCheck_HealthCheck_Call) RunAndReturn(run func() error) *HealthCheck_HealthCheck_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewHealthCheck interface {
	mock.TestingT
	Cleanup(func())
}

// NewHealthCheck creates a new instance of HealthCheck. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewHealthCheck(t mockConstructorTestingTNewHealthCheck) *HealthCheck {
	mock := &HealthCheck{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
