// Code generated by "stringer -type=LogLevel -linecomment"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LogLevelTrace - -8]
	_ = x[LogLevelDebug - -4]
	_ = x[LogLevelInfo-0]
	_ = x[LogLevelWarn-4]
	_ = x[LogLevelError-8]
}

const (
	_LogLevel_name_0 = "TRACE"
	_LogLevel_name_1 = "DEBUG"
	_LogLevel_name_2 = "INFO"
	_LogLevel_name_3 = "WARN"
	_LogLevel_name_4 = "ERROR"
)

func (i LogLevel) String() string {
	switch {
	case i == -8:
		return _LogLevel_name_0
	case i == -4:
		return _LogLevel_name_1
	case i == 0:
		return _LogLevel_name_2
	case i == 4:
		return _LogLevel_name_3
	case i == 8:
		return _LogLevel_name_4
	default:
		return "LogLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
