name: simple-server

env:
  name: local
  type: local
log:
  level: info

httpServer:
  port: 8080
  bindAddress:
  basePath: /api/v1/
  reqLoggerExcludes: [ "/health", "/ready" ]
  cors:
    allowOrigins: ["http://localhost:3000"]
    allowMethods: ["GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS"]
    allowHeaders: ["Origin", "Content-Length", "Content-Type", "Authorization"]
    allowCredentials: false
    allowWildcard: true

slack:
  enabled: true
#  webhookURLs:
#    info: https://hooks.slack.com/services/T01B2JZQZ6V/B01B2JZQZ6V/1B2JZQZ6V

mapping:
  integer: int64
  float: float64
