// Code generated by "stringer -type=MiddlewarePriority -trimprefix=MiddlewarePriority"; DO NOT EDIT.

package middleware

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MiddlewarePriorityNotSet-0]
	_ = x[MiddlewarePriorityHighest-1000]
	_ = x[MiddlewarePriorityBeforeMux-2000]
	_ = x[MiddlewarePriorityAfterMux-3000]
	_ = x[MiddlewarePriorityAuthN-4000]
	_ = x[MiddlewarePriorityAuthZ-5000]
	_ = x[MiddlewarePriorityDefault-6000]
	_ = x[MiddlewarePriorityLowest-9223372036854775807]
}

const (
	_MiddlewarePriority_name_0 = "NotSet"
	_MiddlewarePriority_name_1 = "Highest"
	_MiddlewarePriority_name_2 = "BeforeMux"
	_MiddlewarePriority_name_3 = "AfterMux"
	_MiddlewarePriority_name_4 = "AuthN"
	_MiddlewarePriority_name_5 = "AuthZ"
	_MiddlewarePriority_name_6 = "Default"
	_MiddlewarePriority_name_7 = "Lowest"
)

func (i MiddlewarePriority) String() string {
	switch {
	case i == 0:
		return _MiddlewarePriority_name_0
	case i == 1000:
		return _MiddlewarePriority_name_1
	case i == 2000:
		return _MiddlewarePriority_name_2
	case i == 3000:
		return _MiddlewarePriority_name_3
	case i == 4000:
		return _MiddlewarePriority_name_4
	case i == 5000:
		return _MiddlewarePriority_name_5
	case i == 6000:
		return _MiddlewarePriority_name_6
	case i == 9223372036854775807:
		return _MiddlewarePriority_name_7
	default:
		return "MiddlewarePriority(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
